import { Center, RedistributionRecommendation } from "./types";

export const initialCenters: Center[] = [
  {
    id: "phc-bhubaneswar-north",
    name: "PHC Bhubaneswar North",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र भुवनेश्वर उत्तर",
    lat: 20.296,
    lng: 85.824,
    type: "PHC",
    status: "CRITICAL",
    beds_total: 10,
    beds_occupied: 4,
    doctor_present: true,
    doctor_name: "Dr. Alok Samantaray",
    doctor_absent_days: 0,
    today_patient_count: 58,
    last_report_time: "Today 08:45 AM",
    last_report_days_ago: 0,
    alertMessage: "ORS stock out in 2 days",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 1500, daily_consumption: 120, days_remaining: 12 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 180, daily_consumption: 12, days_remaining: 15 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 120, daily_consumption: 10, days_remaining: 12 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 15, daily_consumption: 5, days_remaining: 3 },
      ORS: { name: "ORS", quantity: 30, daily_consumption: 15, days_remaining: 2 },
      Amoxicillin: { name: "Amoxicillin", quantity: 800, daily_consumption: 50, days_remaining: 16 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 2400, daily_consumption: 150, days_remaining: 16 },
      OCP: { name: "OCP", quantity: 400, daily_consumption: 25, days_remaining: 16 },
      Metronidazole: { name: "Metronidazole", quantity: 600, daily_consumption: 40, days_remaining: 15 },
      Chloroquine: { name: "Chloroquine", quantity: 300, daily_consumption: 10, days_remaining: 30 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 500, daily_consumption: 30, days_remaining: 16 }
    },
    monthly_footfall: [1100, 1250, 1300, 1420, 1500, 1610, 1550, 1480, 1390, 1450, 1510, 1600],
    last_7_days_footfall: [
      { day: "Wed", count: 48 },
      { day: "Thu", count: 52 },
      { day: "Fri", count: 61 },
      { day: "Sat", count: 45 },
      { day: "Sun", count: 12 },
      { day: "Mon", count: 64 },
      { day: "Tue", count: 58 }
    ]
  },
  {
    id: "phc-jatni",
    name: "PHC Jatni",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र जटनी",
    lat: 20.166,
    lng: 85.706,
    type: "PHC",
    status: "WARNING",
    beds_total: 8,
    beds_occupied: 3,
    doctor_present: false,
    doctor_name: "Dr. Sucharita Das",
    doctor_absent_days: 3,
    today_patient_count: 32,
    last_report_time: "Today 09:15 AM",
    last_report_days_ago: 0,
    alertMessage: "Medical Officer absent for 3 consecutive days",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 800, daily_consumption: 90, days_remaining: 8 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 240, daily_consumption: 15, days_remaining: 16 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 90, daily_consumption: 8, days_remaining: 11 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 80, daily_consumption: 6, days_remaining: 13 },
      ORS: { name: "ORS", quantity: 210, daily_consumption: 18, days_remaining: 11 },
      Amoxicillin: { name: "Amoxicillin", quantity: 350, daily_consumption: 30, days_remaining: 11 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 1800, daily_consumption: 110, days_remaining: 16 },
      OCP: { name: "OCP", quantity: 300, daily_consumption: 20, days_remaining: 15 },
      Metronidazole: { name: "Metronidazole", quantity: 400, daily_consumption: 35, days_remaining: 11 },
      Chloroquine: { name: "Chloroquine", quantity: 180, daily_consumption: 15, days_remaining: 12 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 280, daily_consumption: 22, days_remaining: 12 }
    },
    monthly_footfall: [850, 920, 890, 940, 1020, 1100, 1150, 990, 930, 980, 1010, 1050],
    last_7_days_footfall: [
      { day: "Wed", count: 35 },
      { day: "Thu", count: 42 },
      { day: "Fri", count: 38 },
      { day: "Sat", count: 30 },
      { day: "Sun", count: 5 },
      { day: "Mon", count: 41 },
      { day: "Tue", count: 32 }
    ]
  },
  {
    id: "chc-khordha",
    name: "CHC Khordha",
    hindiName: "सामुदायिक स्वास्थ्य केंद्र खोर्धा",
    lat: 20.182,
    lng: 85.606,
    type: "CHC",
    status: "GOOD",
    beds_total: 30,
    beds_occupied: 18,
    doctor_present: true,
    doctor_name: "Dr. Manoranjan Kar",
    doctor_absent_days: 0,
    today_patient_count: 142,
    last_report_time: "Today 08:30 AM",
    last_report_days_ago: 0,
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 8000, daily_consumption: 350, days_remaining: 22 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 1200, daily_consumption: 40, days_remaining: 30 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 800, daily_consumption: 32, days_remaining: 25 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 500, daily_consumption: 20, days_remaining: 25 },
      ORS: { name: "ORS", quantity: 1200, daily_consumption: 45, days_remaining: 26 },
      Amoxicillin: { name: "Amoxicillin", quantity: 2400, daily_consumption: 110, days_remaining: 21 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 5000, daily_consumption: 200, days_remaining: 25 },
      OCP: { name: "OCP", quantity: 1500, daily_consumption: 50, days_remaining: 30 },
      Metronidazole: { name: "Metronidazole", quantity: 1800, daily_consumption: 75, days_remaining: 24 },
      Chloroquine: { name: "Chloroquine", quantity: 950, daily_consumption: 30, days_remaining: 31 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 1400, daily_consumption: 60, days_remaining: 23 }
    },
    monthly_footfall: [2800, 3100, 3300, 3250, 3400, 3700, 3900, 3800, 3500, 3620, 3750, 3900],
    last_7_days_footfall: [
      { day: "Wed", count: 122 },
      { day: "Thu", count: 135 },
      { day: "Fri", count: 140 },
      { day: "Sat", count: 115 },
      { day: "Sun", count: 42 },
      { day: "Mon", count: 155 },
      { day: "Tue", count: 142 }
    ]
  },
  {
    id: "phc-bolagarh",
    name: "PHC Bolagarh",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र बोलगढ़",
    lat: 20.382,
    lng: 85.543,
    type: "PHC",
    status: "WARNING",
    beds_total: 10,
    beds_occupied: 9, // 90%
    doctor_present: true,
    doctor_name: "Dr. Biswanath Patnaik",
    doctor_absent_days: 0,
    today_patient_count: 46,
    last_report_time: "Today 10:02 AM",
    last_report_days_ago: 0,
    alertMessage: "Bed occupancy at 90% capacity limit",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 1100, daily_consumption: 100, days_remaining: 11 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 150, daily_consumption: 10, days_remaining: 15 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 100, daily_consumption: 9, days_remaining: 11 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 60, daily_consumption: 5, days_remaining: 12 },
      ORS: { name: "ORS", quantity: 180, daily_consumption: 20, days_remaining: 9 },
      Amoxicillin: { name: "Amoxicillin", quantity: 450, daily_consumption: 40, days_remaining: 11 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 2100, daily_consumption: 130, days_remaining: 16 },
      OCP: { name: "OCP", quantity: 280, daily_consumption: 20, days_remaining: 14 },
      Metronidazole: { name: "Metronidazole", quantity: 500, daily_consumption: 45, days_remaining: 11 },
      Chloroquine: { name: "Chloroquine", quantity: 200, daily_consumption: 15, days_remaining: 13 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 310, daily_consumption: 25, days_remaining: 12 }
    },
    monthly_footfall: [900, 950, 1010, 1050, 1120, 1200, 1180, 1110, 1030, 1090, 1140, 1220],
    last_7_days_footfall: [
      { day: "Wed", count: 41 },
      { day: "Thu", count: 45 },
      { day: "Fri", count: 49 },
      { day: "Sat", count: 38 },
      { day: "Sun", count: 15 },
      { day: "Mon", count: 50 },
      { day: "Tue", count: 46 }
    ]
  },
  {
    id: "phc-banapur",
    name: "PHC Banapur",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र बाणापुर",
    lat: 20.032,
    lng: 85.526,
    type: "PHC",
    status: "GOOD",
    beds_total: 10,
    beds_occupied: 3,
    doctor_present: true,
    doctor_name: "Dr. Priyadarshini Rout",
    doctor_absent_days: 0,
    today_patient_count: 51,
    last_report_time: "Today 09:30 AM",
    last_report_days_ago: 0,
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 2300, daily_consumption: 110, days_remaining: 20 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 200, daily_consumption: 10, days_remaining: 20 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 160, daily_consumption: 8, days_remaining: 20 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 100, daily_consumption: 5, days_remaining: 20 },
      ORS: { name: "ORS", quantity: 450, daily_consumption: 22, days_remaining: 20 },
      Amoxicillin: { name: "Amoxicillin", quantity: 900, daily_consumption: 45, days_remaining: 20 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 3000, daily_consumption: 140, days_remaining: 21 },
      OCP: { name: "OCP", quantity: 600, daily_consumption: 25, days_remaining: 24 },
      Metronidazole: { name: "Metronidazole", quantity: 1100, daily_consumption: 50, days_remaining: 22 },
      Chloroquine: { name: "Chloroquine", quantity: 400, daily_consumption: 18, days_remaining: 22 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 700, daily_consumption: 30, days_remaining: 23 }
    },
    monthly_footfall: [1150, 1200, 1180, 1260, 1310, 1400, 1370, 1290, 1220, 1280, 1350, 1420],
    last_7_days_footfall: [
      { day: "Wed", count: 45 },
      { day: "Thu", count: 48 },
      { day: "Fri", count: 53 },
      { day: "Sat", count: 39 },
      { day: "Sun", count: 8 },
      { day: "Mon", count: 56 },
      { day: "Tue", count: 51 }
    ]
  },
  {
    id: "phc-tangi",
    name: "PHC Tangi",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र टांगी",
    lat: 20.282,
    lng: 85.926,
    type: "PHC",
    status: "CRITICAL",
    beds_total: 12,
    beds_occupied: 7,
    doctor_present: true,
    doctor_name: "Dr. Sanjay Kumar Jena",
    doctor_absent_days: 0,
    today_patient_count: 65,
    last_report_time: "Today 08:15 AM",
    last_report_days_ago: 0,
    alertMessage: "Paracetamol stock out in 1 day",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 150, daily_consumption: 150, days_remaining: 1 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 10, daily_consumption: 15, days_remaining: 0 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 220, daily_consumption: 10, days_remaining: 22 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 180, daily_consumption: 9, days_remaining: 20 },
      ORS: { name: "ORS", quantity: 380, daily_consumption: 25, days_remaining: 15 },
      Amoxicillin: { name: "Amoxicillin", quantity: 1100, daily_consumption: 55, days_remaining: 20 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 3200, daily_consumption: 160, days_remaining: 20 },
      OCP: { name: "OCP", quantity: 500, daily_consumption: 20, days_remaining: 25 },
      Metronidazole: { name: "Metronidazole", quantity: 950, daily_consumption: 45, days_remaining: 21 },
      Chloroquine: { name: "Chloroquine", quantity: 380, daily_consumption: 15, days_remaining: 25 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 600, daily_consumption: 30, days_remaining: 20 }
    },
    monthly_footfall: [1200, 1310, 1390, 1450, 1500, 1620, 1580, 1490, 1410, 1470, 1550, 1650],
    last_7_days_footfall: [
      { day: "Wed", count: 58 },
      { day: "Thu", count: 62 },
      { day: "Fri", count: 67 },
      { day: "Sat", count: 50 },
      { day: "Sun", count: 18 },
      { day: "Mon", count: 72 },
      { day: "Tue", count: 65 }
    ]
  },
  {
    id: "chc-begunia",
    name: "CHC Begunia",
    hindiName: "सामुदायिक स्वास्थ्य केंद्र बेगुनिया",
    lat: 20.131,
    lng: 85.459,
    type: "CHC",
    status: "GOOD",
    beds_total: 24,
    beds_occupied: 11,
    doctor_present: true,
    doctor_name: "Dr. Sudhanshu Sekhar Sahoo",
    doctor_absent_days: 0,
    today_patient_count: 112,
    last_report_time: "Today 09:45 AM",
    last_report_days_ago: 0,
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 5200, daily_consumption: 240, days_remaining: 21 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 800, daily_consumption: 30, days_remaining: 26 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 500, daily_consumption: 20, days_remaining: 25 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 400, daily_consumption: 15, days_remaining: 26 },
      ORS: { name: "ORS", quantity: 950, daily_consumption: 35, days_remaining: 27 },
      Amoxicillin: { name: "Amoxicillin", quantity: 1800, daily_consumption: 80, days_remaining: 22 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 4100, daily_consumption: 170, days_remaining: 24 },
      OCP: { name: "OCP", quantity: 1100, daily_consumption: 40, days_remaining: 27 },
      Metronidazole: { name: "Metronidazole", quantity: 1300, daily_consumption: 60, days_remaining: 21 },
      Chloroquine: { name: "Chloroquine", quantity: 720, daily_consumption: 25, days_remaining: 28 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 1100, daily_consumption: 50, days_remaining: 22 }
    },
    monthly_footfall: [2100, 2250, 2400, 2380, 2500, 2750, 2800, 2690, 2520, 2580, 2650, 2800],
    last_7_days_footfall: [
      { day: "Wed", count: 98 },
      { day: "Thu", count: 105 },
      { day: "Fri", count: 112 },
      { day: "Sat", count: 89 },
      { day: "Sun", count: 28 },
      { day: "Mon", count: 121 },
      { day: "Tue", count: 112 }
    ]
  },
  {
    id: "phc-chilika",
    name: "PHC Chilika",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र चिलिका",
    lat: 19.983,
    lng: 85.467,
    type: "PHC",
    status: "WARNING",
    beds_total: 10,
    beds_occupied: 5,
    doctor_present: true,
    doctor_name: "Dr. Laxmidhar Sethy",
    doctor_absent_days: 0,
    today_patient_count: 42,
    last_report_time: "Today 10:10 AM",
    last_report_days_ago: 0,
    alertMessage: "Low stock multiple critical medicines",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 400, daily_consumption: 100, days_remaining: 4 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 50, daily_consumption: 10, days_remaining: 5 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 40, daily_consumption: 8, days_remaining: 5 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 30, daily_consumption: 5, days_remaining: 6 },
      ORS: { name: "ORS", quantity: 100, daily_consumption: 20, days_remaining: 5 },
      Amoxicillin: { name: "Amoxicillin", quantity: 240, daily_consumption: 40, days_remaining: 6 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 1400, daily_consumption: 120, days_remaining: 11 },
      OCP: { name: "OCP", quantity: 250, daily_consumption: 20, days_remaining: 12 },
      Metronidazole: { name: "Metronidazole", quantity: 310, daily_consumption: 45, days_remaining: 6 },
      Chloroquine: { name: "Chloroquine", quantity: 100, daily_consumption: 15, days_remaining: 6 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 200, daily_consumption: 25, days_remaining: 8 }
    },
    monthly_footfall: [890, 940, 990, 1020, 1080, 1150, 1120, 1050, 980, 1020, 1090, 1160],
    last_7_days_footfall: [
      { day: "Wed", count: 36 },
      { day: "Thu", count: 41 },
      { day: "Fri", count: 45 },
      { day: "Sat", count: 35 },
      { day: "Sun", count: 12 },
      { day: "Mon", count: 48 },
      { day: "Tue", count: 42 }
    ]
  },
  {
    id: "phc-nimapara",
    name: "PHC Nimapara",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र निमापड़ा",
    lat: 20.066,
    lng: 85.998,
    type: "PHC",
    status: "GOOD",
    beds_total: 8,
    beds_occupied: 4,
    doctor_present: true,
    doctor_name: "Dr. Jyoti Ranjan Mallick",
    doctor_absent_days: 0,
    today_patient_count: 45,
    last_report_time: "Today 09:20 AM",
    last_report_days_ago: 0,
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 2100, daily_consumption: 100, days_remaining: 21 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 180, daily_consumption: 9, days_remaining: 20 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 150, daily_consumption: 7, days_remaining: 21 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 110, daily_consumption: 5, days_remaining: 22 },
      ORS: { name: "ORS", quantity: 380, daily_consumption: 18, days_remaining: 21 },
      Amoxicillin: { name: "Amoxicillin", quantity: 720, daily_consumption: 35, days_remaining: 20 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 2500, daily_consumption: 120, days_remaining: 20 },
      OCP: { name: "OCP", quantity: 480, daily_consumption: 20, days_remaining: 24 },
      Metronidazole: { name: "Metronidazole", quantity: 850, daily_consumption: 40, days_remaining: 21 },
      Chloroquine: { name: "Chloroquine", quantity: 350, daily_consumption: 15, days_remaining: 23 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 580, daily_consumption: 25, days_remaining: 23 }
    },
    monthly_footfall: [1020, 1100, 1080, 1150, 1210, 1300, 1260, 1190, 1130, 1180, 1240, 1310],
    last_7_days_footfall: [
      { day: "Wed", count: 40 },
      { day: "Thu", count: 43 },
      { day: "Fri", count: 48 },
      { day: "Sat", count: 32 },
      { day: "Sun", count: 6 },
      { day: "Mon", count: 49 },
      { day: "Tue", count: 45 }
    ]
  },
  {
    id: "phc-pipili",
    name: "PHC Pipili",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र पिपिली",
    lat: 20.133,
    lng: 85.876,
    type: "PHC",
    status: "GOOD",
    beds_total: 12,
    beds_occupied: 6,
    doctor_present: true,
    doctor_name: "Dr. Satyabrata Tripathy",
    doctor_absent_days: 0,
    today_patient_count: 70,
    last_report_time: "Today 08:50 AM",
    last_report_days_ago: 0,
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 3400, daily_consumption: 160, days_remaining: 21 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 300, daily_consumption: 15, days_remaining: 20 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 240, daily_consumption: 10, days_remaining: 24 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 160, daily_consumption: 8, days_remaining: 20 },
      ORS: { name: "ORS", quantity: 600, daily_consumption: 25, days_remaining: 24 },
      Amoxicillin: { name: "Amoxicillin", quantity: 1200, daily_consumption: 55, days_remaining: 21 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 4200, daily_consumption: 180, days_remaining: 23 },
      OCP: { name: "OCP", quantity: 720, daily_consumption: 30, days_remaining: 24 },
      Metronidazole: { name: "Metronidazole", quantity: 1400, daily_consumption: 65, days_remaining: 21 },
      Chloroquine: { name: "Chloroquine", quantity: 480, daily_consumption: 20, days_remaining: 24 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 900, daily_consumption: 40, days_remaining: 22 }
    },
    monthly_footfall: [1400, 1520, 1590, 1650, 1720, 1850, 1800, 1710, 1630, 1690, 1780, 1880],
    last_7_days_footfall: [
      { day: "Wed", count: 62 },
      { day: "Thu", count: 68 },
      { day: "Fri", count: 74 },
      { day: "Sat", count: 55 },
      { day: "Sun", count: 18 },
      { day: "Mon", count: 79 },
      { day: "Tue", count: 70 }
    ]
  },
  {
    id: "phc-delang",
    name: "PHC Delang",
    hindiName: "प्राथमिक स्वास्थ्य केंद्र डेलंग",
    lat: 20.216,
    lng: 85.759,
    type: "PHC",
    status: "WARNING",
    beds_total: 8,
    beds_occupied: 2,
    doctor_present: true,
    doctor_name: "Dr. Soumya Ranjan Kar",
    doctor_absent_days: 0,
    today_patient_count: 0,
    last_report_time: "2 days ago 09:00 AM",
    last_report_days_ago: 2,
    alertMessage: "Missing daily health reports for 2 consecutive days",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 1200, daily_consumption: 100, days_remaining: 12 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 120, daily_consumption: 10, days_remaining: 12 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 96, daily_consumption: 8, days_remaining: 12 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 60, daily_consumption: 5, days_remaining: 12 },
      ORS: { name: "ORS", quantity: 240, daily_consumption: 20, days_remaining: 12 },
      Amoxicillin: { name: "Amoxicillin", quantity: 480, daily_consumption: 40, days_remaining: 12 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 1600, daily_consumption: 130, days_remaining: 12 },
      OCP: { name: "OCP", quantity: 300, daily_consumption: 25, days_remaining: 12 },
      Metronidazole: { name: "Metronidazole", quantity: 540, daily_consumption: 45, days_remaining: 12 },
      Chloroquine: { name: "Chloroquine", quantity: 180, daily_consumption: 15, days_remaining: 12 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 300, daily_consumption: 25, days_remaining: 12 }
    },
    monthly_footfall: [920, 980, 950, 1010, 1060, 1120, 1090, 1020, 960, 1000, 1050, 1110],
    last_7_days_footfall: [
      { day: "Wed", count: 38 },
      { day: "Thu", count: 42 },
      { day: "Fri", count: 44 },
      { day: "Sat", count: 31 },
      { day: "Sun", count: 4 },
      { day: "Mon", count: 0 },
      { day: "Tue", count: 0 }
    ]
  },
  {
    id: "chc-balugaon",
    name: "CHC Balugaon",
    hindiName: "सामुदायिक स्वास्थ्य केंद्र बालूगाँव",
    lat: 19.899,
    lng: 85.243,
    type: "CHC",
    status: "CRITICAL",
    beds_total: 20,
    beds_occupied: 13,
    doctor_present: false,
    doctor_name: "Dr. Niranjan Behera",
    doctor_absent_days: 5,
    today_patient_count: 85,
    last_report_time: "Today 08:00 AM",
    last_report_days_ago: 0,
    alertMessage: "No medical officer present for 5 consecutive days",
    stock: {
      Paracetamol: { name: "Paracetamol", quantity: 3800, daily_consumption: 180, days_remaining: 21 },
      "Malaria RDT Kit": { name: "Malaria RDT Kit", quantity: 600, daily_consumption: 25, days_remaining: 24 },
      "Pregnancy Test Kit": { name: "Pregnancy Test Kit", quantity: 400, daily_consumption: 16, days_remaining: 25 },
      "Dengue NS1 Kit": { name: "Dengue NS1 Kit", quantity: 300, daily_consumption: 12, days_remaining: 25 },
      ORS: { name: "ORS", quantity: 800, daily_consumption: 30, days_remaining: 26 },
      Amoxicillin: { name: "Amoxicillin", quantity: 1400, daily_consumption: 65, days_remaining: 21 },
      "Iron Tablets": { name: "Iron Tablets", quantity: 3500, daily_consumption: 150, days_remaining: 23 },
      OCP: { name: "OCP", quantity: 800, daily_consumption: 30, days_remaining: 26 },
      Metronidazole: { name: "Metronidazole", quantity: 1100, daily_consumption: 50, days_remaining: 22 },
      Chloroquine: { name: "Chloroquine", quantity: 500, daily_consumption: 20, days_remaining: 25 },
      Cotrimoxazole: { name: "Cotrimoxazole", quantity: 800, daily_consumption: 35, days_remaining: 22 }
    },
    monthly_footfall: [1800, 1950, 2100, 2050, 2200, 2400, 2350, 2210, 2130, 2190, 2280, 2380],
    last_7_days_footfall: [
      { day: "Wed", count: 88 },
      { day: "Thu", count: 91 },
      { day: "Fri", count: 95 },
      { day: "Sat", count: 78 },
      { day: "Sun", count: 25 },
      { day: "Mon", count: 82 },
      { day: "Tue", count: 85 }
    ]
  }
];

export const mockRedistributions: RedistributionRecommendation[] = [
  {
    id: "rec-1",
    fromCenter: "CHC Khordha",
    item: "Paracetamol",
    qtyToTransfer: 800,
    toCenter: "PHC Tangi",
    distance: 12.4,
    priority: "HIGH"
  },
  {
    id: "rec-2",
    fromCenter: "CHC Begunia",
    item: "ORS",
    qtyToTransfer: 200,
    toCenter: "PHC Bhubaneswar North",
    distance: 18.2,
    priority: "MEDIUM"
  },
  {
    id: "rec-3",
    fromCenter: "CHC Khordha",
    item: "Amoxicillin",
    qtyToTransfer: 300,
    toCenter: "PHC Chilika",
    distance: 21.5,
    priority: "MEDIUM"
  }
];

export const mockAnalyticsData = {
  footfall30Days: [
    { date: "06/08", patients: 680 },
    { date: "06/10", patients: 710 },
    { date: "06/12", patients: 735 },
    { date: "06/14", patients: 690 },
    { date: "06/16", patients: 750 },
    { date: "06/18", patients: 780 },
    { date: "06/20", patients: 742 },
    { date: "06/22", patients: 765 },
    { date: "06/24", patients: 790 },
    { date: "06/26", patients: 810 },
    { date: "06/28", patients: 835 },
    { date: "06/30", patients: 795 },
    { date: "07/02", patients: 820 },
    { date: "07/04", patients: 845 },
    { date: "07/06", patients: 814 }
  ],
  stockHealth: [
    { center: "PHC Bhubaneswar North", ORS: 2, Paracetamol: 12, Amoxicillin: 16 },
    { center: "PHC Jatni", ORS: 11, Paracetamol: 8, Amoxicillin: 11 },
    { center: "PHC Bolagarh", ORS: 9, Paracetamol: 11, Amoxicillin: 11 },
    { center: "PHC Tangi", ORS: 15, Paracetamol: 1, Amoxicillin: 20 },
    { center: "PHC Chilika", ORS: 5, Paracetamol: 4, Amoxicillin: 6 },
    { center: "PHC Delang", ORS: 12, Paracetamol: 12, Amoxicillin: 12 }
  ],
  attendanceRate: [
    { date: "Wed", "PHC Bhubaneswar North": 100, "PHC Jatni": 0, "CHC Khordha": 100, "CHC Balugaon": 0 },
    { date: "Thu", "PHC Bhubaneswar North": 100, "PHC Jatni": 0, "CHC Khordha": 100, "CHC Balugaon": 0 },
    { date: "Fri", "PHC Bhubaneswar North": 100, "PHC Jatni": 0, "CHC Khordha": 100, "CHC Balugaon": 0 },
    { date: "Sat", "PHC Bhubaneswar North": 100, "PHC Jatni": 0, "CHC Khordha": 100, "CHC Balugaon": 0 },
    { date: "Sun", "PHC Bhubaneswar North": 50, "PHC Jatni": 0, "CHC Khordha": 100, "CHC Balugaon": 0 },
    { date: "Mon", "PHC Bhubaneswar North": 100, "PHC Jatni": 100, "CHC Khordha": 100, "CHC Balugaon": 0 },
    { date: "Tue", "PHC Bhubaneswar North": 100, "PHC Jatni": 0, "CHC Khordha": 100, "CHC Balugaon": 0 }
  ]
};
